version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "alembic upgrade head && poetry run uvicorn app:app --host 0.0.0.0 --port 8000"

  postgres:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    env_file:
      - .docker/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - static_storage:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address :9001
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  createbucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --api s3v4 s3 http://minio:9000 user password;
      /usr/bin/mc mb s3/static/;
      /usr/bin/mc anonymous set download s3/static;
      "

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-server
    volumes:
      - .docker/clickhouse_data:/var/lib/clickhouse
      - .docker/clickhouse/init-clickhouse.sql:/docker-entrypoint-initdb.d/init-clickhouse.sql
      - .docker/clickhouse/clickhouse-config/users.xml:/etc/clickhouse-server/users.d/users.xml

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./.docker/nginx/
    container_name: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    env_file:
      - .docker/.env
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
      - "9001:9001"

volumes:
  postgres_storage:
  clickhouse_storage:
  static_storage:
